"""
GlaucoSense - train_model.py
Owner: M3 (ML)
Purpose: Trains and cross-validates two simple stiffness classifiers
         (Logistic Regression and Decision Tree) on data/features.csv +
         data/labels.csv, then exports the Logistic Regression model as a C
         header (model_config.h) so Member 3 can drop it into
         firmware/GlaucoSense_Final/model_inference.h in place of the
         placeholder threshold classifier.

NOT a medical device. Bench-test prototype only.
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

FEATURES_CSV = "data/features.csv"
LABELS_CSV = "data/labels.csv"
MODEL_HEADER = "model_config.h"

FEATURE_COLUMNS = [
    "baseline_mm", "max_deform_mm", "time_to_max_ms",
    "recovery_ms", "peak_pressure_kpa", "pressure_drop_kpa",
]


def load_dataset():
    features = pd.read_csv(FEATURES_CSV)
    labels = pd.read_csv(LABELS_CSV)
    data = features.merge(labels, on="trial")
    X = data[FEATURE_COLUMNS].to_numpy(dtype=float)
    y = data["label"].to_numpy(dtype=int)
    return X, y


def c_array(name, values):
    values_str = ", ".join(f"{v:.8f}f" for v in values)
    return f"const float {name}[{len(values)}] = {{ {values_str} }};"


def export_model_config_h(scaler, model, path):
    mean = scaler.mean_
    std = scaler.scale_
    coef = model.coef_
    intercept = model.intercept_

    if coef.shape[0] == 1:
        # sklearn collapses binary problems to a single row - keep 2 rows
        # so the on-device code always deals with one row per class.
        coef = np.vstack([-coef[0], coef[0]])
        intercept = np.array([-intercept[0], intercept[0]])

    lines = [
        "/*",
        " * GlaucoSense - model_config.h (AUTO-GENERATED by train_model.py)",
        " * Owner: M3 (ML)",
        " * Purpose: Exported Logistic Regression weights for the stiffness",
        " *          classifier. Do not hand-edit this file - rerun",
        " *          train_model.py instead.",
        " *",
        " * NOT a medical device. Bench-test prototype only.",
        " */",
        "",
        "#ifndef MODEL_CONFIG_H",
        "#define MODEL_CONFIG_H",
        "",
        f"#define MODEL_NUM_FEATURES {len(mean)}",
        f"#define MODEL_NUM_CLASSES {coef.shape[0]}",
        "",
        c_array("FEAT_MEAN", mean),
        c_array("FEAT_STD", std),
        "",
    ]

    for class_index in range(coef.shape[0]):
        lines.append(c_array(f"COEF_CLASS{class_index}", coef[class_index]))
    lines.append("")
    lines.append(c_array("INTERCEPT", intercept))
    lines.append("")
    lines.append("#endif // MODEL_CONFIG_H")
    lines.append("")

    with open(path, "w") as f:
        f.write("\n".join(lines))

    print(f"Exported model weights to {path}")


def main():
    X, y = load_dataset()

    if len(y) < 4 or len(set(y)) < 2:
        print("Not enough data yet to train (need several trials covering more "
              "than one stiffness class). Collect more trials, then rerun this script.")
        return

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    logreg = LogisticRegression(max_iter=1000)
    tree = DecisionTreeClassifier(max_depth=4, random_state=0)

    cv_folds = min(5, len(y))
    logreg_scores = cross_val_score(logreg, X_scaled, y, cv=cv_folds)
    tree_scores = cross_val_score(tree, X, y, cv=cv_folds)

    print(f"Logistic Regression cross-val accuracy: {logreg_scores.mean():.3f} (+/- {logreg_scores.std():.3f})")
    print(f"Decision Tree cross-val accuracy:        {tree_scores.mean():.3f} (+/- {tree_scores.std():.3f})")

    # Fit on all available data and export the Logistic Regression model.
    logreg.fit(X_scaled, y)
    export_model_config_h(scaler, logreg, MODEL_HEADER)


if __name__ == "__main__":
    main()
